import java.time.Instant
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

/**
 * A build identifier that changes with every build, so the owner can tell which
 * sideloaded APK is installed. It is generated by Gradle (UTC) rather than passed
 * in by CI, so a local build is identifiable too.
 */
val buildIdentifier: String = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm 'UTC'")
    .withZone(ZoneOffset.UTC)
    .format(Instant.now())

android {
    namespace = "com.misaka9981.alarm"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.misaka9981.alarm"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "0.1.0"

        buildConfigField("String", "BUILD_IDENTIFIER", "\"$buildIdentifier\"")
    }

    // A fixed, committed debug keystore. It is intentionally non-secret: it only
    // signs debug builds so CI can produce an installable APK that upgrades in
    // place, something a per-runner generated debug key cannot do. See ADR-0001.
    signingConfigs {
        create("debugFixed") {
            storeFile = rootProject.file("keystore/debug.keystore")
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
        }
    }

    buildTypes {
        getByName("debug") {
            signingConfig = signingConfigs.getByName("debugFixed")
        }
        getByName("release") {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

dependencies {
    // The only source of decidable logic in the app.
    implementation(project(":core"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation(libs.androidx.datastore.preferences)

    // Camera-based Physical Anchor scanning. The decision it feeds lives in :core.
    implementation(libs.google.play.services.code.scanner)

    debugImplementation(libs.androidx.ui.tooling)
}
